### ISSUE TITLE
Configuration __init__ doesn't accept "access_token"

### ISSUE THREAD

**Issue by majkshkurti** [p2-inc/phasetwo-python#3]
Is there any other way to init the configuration? 

The following example shown in the readme doesn't seem to work as the argument `'access_token'` isn't accepted from the Configuration Class. 

```
configuration = phasetwo.Configuration(
    host = "https://app.phasetwo.io/auth/realms"
    access_token = keycloak_admin.token()
)
```
Thank you.

**Comment by xgp** [comment]
Good catch. Looks like this got accidentally clobbered in a recent update. Will add it back.

**Comment by xgp** [comment]
5fbdfb1
